name: tuallergycare
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  material_buttonx:
  provider: ^3.0.0
  intl: ^0.15.8
  http: ^0.12.0+2
  expandable: ^5.0.1
  qr_code_scanner: ^0.4.0
  simple_animations: ^1.3.4
  table_calendar: ^2.2.3
  grouped_list: ^4.0.0 
  badges: ^1.2.0
  flutter_barcode_scanner: ^1.0.1
  
  
  

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/cry.png
    - assets/images/sad.png
    - assets/images/scary.png
    - assets/images/smile.png
    - assets/images/avamys.png
    - assets/images/tu.png
    - assets/images/login.png
    - assets/images/assessment.png
    - assets/images/patient.png
    - assets/images/drugtoday.png
    - assets/images/qrcode.png
    - assets/images/medicinebox.png
    - assets/images/dymista.jpeg
    - assets/images/nasonex.jpeg
    - assets/images/allernix.png
    - assets/images/telfast.png
    - assets/images/aerius.png
    - assets/images/bilaxten.jpeg
    - assets/images/zyrtec.png
    - assets/images/xyzal.png
    - assets/images/head.png
    - assets/images/pone.png
    - assets/images/ptwo.png
    - assets/images/ptree.png
    - assets/images/pfour.png
    - assets/images/pfive.png
    - assets/images/status_green.png
    - assets/images/status_red.png
    - assets/images/status_yellow.png
    - assets/images/status_orange.png


    

    
    # - assets/images/assessment.png
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

